# Class Imbalance -- Sampling // Undersampling // Oversampling // Smote ...

# Imbalance Datasetda Weight berish -- og'irlik berish orqali imbalance datasetni togirlash

# Matematik Tomondan 
- Loss = wi*L(y,y^) -- bu formulasi
- Minority class --> Katta weight
- Mijority class --> Kichik weight

In [1]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(class_weight="balanced")

# class_weight = "balanced" -- bu nima qiladi?
- Kam classga katta weight qoshish orqali balancega keltiradi

# Custom weight berish -- o'zimiz bilgan holda aniq qiymat bilan balance berishimiz ham mumkin

In [2]:
model = DecisionTreeClassifier(class_weight={0:1, 1:10})  # bu degani class 1 --> 10 barobar muhim

# Imbalance datasetlarda quyidagicha balanslash holatlarini ishlatamiz

| Holat | Yechim | Tushuntirish |
| :--- | :--- | :--- |
| **Data kam** | SMOTE | Kam sonli klassga sun'iy ma'lumot qo'shadi |
| **Data katta** | Undersampling | Ko'p sonli klass ma'lumotlarini kamaytiradi |
| **Tez yechim** | `class_weight='balanced'` | Ma'lumotga tegmasdan, modelda vazn ajratadi |
| **Deep learning** | Loss weighting | Focal Loss yoki maxsus vaznli Loss funksiya ishlatadi |

In [3]:
import seaborn as sns 
import pandas as pd

df = sns.load_dataset("titanic")

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [6]:
df = df[["pclass", "sex", "age", "fare", "survived"]]

In [7]:
df.head()

   pclass     sex   age     fare  survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   fare      891 non-null    float64
 4   survived  891 non-null    int64
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB

In [9]:
df["age"] = df["age"].fillna(df["age"].mean())

C:\Users\Jahongir\AppData\Local\Temp\ipykernel_11312\1809447586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age"] = df["age"].fillna(df["age"].mean())

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       891 non-null    float64
 3   fare      891 non-null    float64
 4   survived  891 non-null    int64
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB

In [12]:
df["sex"] = df["sex"].map({"male":0, "female":1})

C:\Users\Jahongir\AppData\Local\Temp\ipykernel_11312\594780884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sex"] = df["sex"].map({"male":0, "female":1})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    int64
 2   age       891 non-null    float64
 3   fare      891 non-null    float64
 4   survived  891 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB

In [16]:
x = df.drop("survived", axis=1)
y = df["survived"]

In [21]:
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

# Class Weight No Balanced

In [22]:
from sklearn.tree import DecisionTreeClassifier

model_no_weight = DecisionTreeClassifier(random_state=42)
model_no_weight.fit(x_train,y_train)

y_pred_no = model_no_weight.predict(x_test)

In [23]:
from sklearn.metrics import classification_report

print("without class weight")
print(classification_report(y_test, y_pred_no))

without class weight
              precision    recall  f1-score   support

           0       0.78      0.76      0.77       105
           1       0.68      0.70      0.69        74

    accuracy                           0.74       179
   macro avg       0.73      0.73      0.73       179
weighted avg       0.74      0.74      0.74       179

# Class Weight Balanced

In [24]:
model_weight = DecisionTreeClassifier(class_weight="balanced", random_state=42)


model_weight.fit(x_train, y_train)

y_pred_weight = model_weight.predict(x_test)

In [ ]:
print("class_weight='balanced'")
print(classification_report(y_test, y_pred_weight))

class_weight='balanced'
              precision    recall  f1-score   support

           0       0.81      0.78      0.80       105
           1       0.71      0.74      0.72        74

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179

# Class Weight Custom == o'zimiz Custom xolatda beramiz

In [26]:
model_custom = DecisionTreeClassifier(class_weight={0:1, 1:3}, random_state=42)

model_custom.fit(x_train, y_train)

y_pred_custom = model_custom.predict(x_test)

In [31]:
print("Custom = class_weight")
print(classification_report(y_test, y_pred_custom))

Custom = class_weight
              precision    recall  f1-score   support

           0       0.81      0.79      0.80       105
           1       0.71      0.73      0.72        74

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179

# Hamma algorithmlarda ham CLASS_WEIGHT ishlamaydi

- Agarda model loss function optimizatsiya qilsa --> class_weight ishlaydi
- Agarda model distance yoki rule based bolsa --> class_weight ishlamaydi

# class_weight ishlaydigan modellar 
- Decision tree 
- Random Forest 
- Extra Trees
- Logistic Regression
- SVM


# Boosting algorithmlari ham bor 
- XGBOOST
- LightGBM
- CatBOOST

# Class_Weight ishlamaydigan modellar 

- KNN
- Naive Bayes
- Clustering algorithmlar